[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bank = "41XVEDSnAPRyo987ceqC3uFa3tw8acVgHW6FuD4crqLg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nikpopo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
